### ISSUE TITLE
Black flashing screen when recording video (also saved in the recording)

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#1249]
### Which implementation are you using

*RNCamera*

### Steps to reproduce

1. Mount a video component with autoFocus on
2. Use the reference prop to start recording when pressing the screen

### Expected behaviour
The video start recording without the black going screen for a few milliseconds. Also the video should be saved without black frames at the beginning

### Actual behaviour
The screen turns black for a few milliseconds. The few milliseconds of dark frames are also present in the recording. I think this is related to autoFocus.

### Environment
- **Node.js version**: v8.9.4
- **React Native version**: v0.52.2
- **React Native platform + platform version**: iOS 10

### react-native-camera
**Version**: v1.0.1

**Comment by n1ru4l** [comment]
Duplicate of https://github.com/expo/expo/issues/1057

**Comment by n1ru4l** [comment]
@jgfidelis @sibelius Would you accept a PR on `RNCamera` that implements a property for the current mode (`recording` and `picture`), in order to prevent the flashing when recording?

Also there must be a solution to this problem, bot snapchat and instagram can handle this, so it should not be impossible. We might get some inspiration (or even reuse?) some open source solution which is written in objective-c?

**Comment by sibelius** [comment]
We will accept a PR to fix this

**Comment by n1ru4l** [comment]
@delta98 Any ideas what snapchat/instagram is doing differently? Because from what I can see they are also switching between the modes without flashings

**Comment by delta98** [comment]
@n1ru4l it looks like it happens after calling `[self setupMovieFileCapture];`

**Comment by delta98** [comment]
Actually nailed this down even further, when `record` is called, the `session` configuration is changed, this causes the current session to be unlocked, which causes the flicker. 

`updateSessionPreset` and `updateSessionAudioIsMuted` use this within their function calls. 

Removing these calls from record and moving `setupMovieFileCapture` to `initializeCaptureSessionInput` or `initWithBridge` allows capture to active more _seamless_. 

I'll put a PR together which takes into account the above and provides the same functionality, but likely will need to limit the camera mode to an instance of camera.

**Comment by delta98** [comment]
@n1ru4l could you checkout this branch and confirm whether this stops the flicker you see https://github.com/react-native-community/react-native-camera/pull/1542

Will also need to soften some of the changes and re-introduce functionality for face detection.

**Comment by delta98** [comment]
@sibelius ^^

**Comment by n1ru4l** [comment]
@delta98 Will try to do it tomorrow

**Comment by watadarkstar** [comment]
Following! Will test this out. Hows the PR going @n1ru4l ?

**Comment by n1ru4l** [comment]
@watadarkstar I am using it in production 😉

**Comment by pqminh** [comment]
How to fix it?

**Comment by n1ru4l** [comment]
@pqminh my current workaround is described here: https://github.com/react-native-community/react-native-camera/pull/1542#issuecomment-407324574

If you want to use the newest master you will have to adjust it.

I still had no time to file in a pull request 😕

**Comment by pqminh** [comment]
@n1ru4l tks. I'm trying now.

**Comment by listicos** [comment]
Hello, I just created a simple solution for this https://github.com/react-native-community/react-native-camera/pull/1886

**Comment by n1ru4l** [comment]
Fixed in #1886

**Comment by Thanhcao86** [comment]
I tried but still encountered this situation again in the second video recording, I thought because of some method called back wrongly, I tried to read and cancel some unnecessary methods for my project but didn't work effective.
I tried again, I found out that during the second video recording, the camera's status was again blinking, I tried to delete this method [CleanupCamera], it no longer flashes but after the second time it has an exception with "Video is not recorded". I am still looking for a solution, hoping to help this situation.
