### ISSUE TITLE
Permissions problem with React Native v0.56 and Android API<=22

### ISSUE THREAD

**Issue by jorgifumi** [react-native-community/react-native-camera#1707]
### Steps to reproduce
1. Create a new react native project with version 56 or higher.
2. Install react-native-camera
3. Open the app in a device with Android 5.1 or lower (API 22) and navigate to camera screen

### Expected behaviour
The preview of the camera should render.

### Actual behaviour
The notAuthorizedView renders.

### Environment
- **React Native version**: 0.56.0
- **React Native platform + platform version**: Android 5.1

### react-native-camera
**Version**: tested in both npm version 1.1.4 and "master" 1.1.5

After getting crazy trying a lot of solutions, I downgraded to React Native 0.55.3 and it started to work as expected. This issue does not happen in iOS or Android API versions 23 and upper.

**Comment by jgfidelis** [comment]
It is probably because until RN 0.53 for android <= 23 there was a bug on the PermissionsAndroid lib. It was fixed n RN 0.54 or RN 0.56, someone should send a pr correcting the way we check permissions for android <=23, should not be difficult.

**Comment by ivosabev** [comment]
It is fixed by this commit - https://github.com/react-native-community/react-native-camera/commit/07496bb17b641c8b2732615ad40ff6d77b0acb5a

**Comment by sebastianor** [comment]
Hello, i still have this problem. My RN version i 0.56 and Android Version i 5.1.1. PermissionsAndroid lib returns that i permissions is granted but i still getting message: "Camera is not authorized".

**Comment by sibelius** [comment]
@sebastianor can u try master?

**Comment by sebastianor** [comment]
I have installed this by command `npm install react-native-camera --save` so i guess that i've used master branch. I have 1.1.4 version of react-native-camera.

**Comment by sibelius** [comment]
neh, master branch has more commits I guess

**Comment by sebastianor** [comment]
Could you tell me how to install it ?

**Comment by n1ru4l** [comment]
@sebastianor `yarn add react-native-camera@git+https://github.com/react-native-community/react-native-camera.git#860662e0b0e5668503fd6119867abf62b789f677`

**Comment by sebastianor** [comment]
It does not help. Camera still not works

**Comment by sebastianor** [comment]
Okay it works when you switch on master. Sorry my mistake.

**Comment by mcclen** [comment]
I am unable to get RNCamera to work on a Nexus 5 with 4.4.4 installed. The application works really well on emulators above Android 6 and iOS emulators and devices 9.3 and above. The problem seems to be about permissions and the authorization failure occurs for both the Nexus 5 device and any emulator configured at less than Android 6.

Using this to install react-native-camera 1.1.5 -
`
npm install react-native-camera@git+https://github.com/react-native-community/react-native-camera.git#860662e0b0e5668503fd6119867abf62b789f677
`

I have the appropriate permission request per the documentation in the application manifest.

Any help appreciated.

**Comment by ivosabev** [comment]
We cannot make it work for anything below API Level 21 (5.0) as well, but it is not the permissions crashing - https://github.com/react-native-community/react-native-camera/issues/1701

**Comment by afrakhan123** [comment]
I am having the same problem android 4.4.4 and react native 0.55.4

**Comment by ortimanu** [comment]
We are having problems on some Androids OS 5 of our users with this same configuration. Any updates?
