### ISSUE TITLE
Android: captured image is always rotated

### ISSUE THREAD

**Issue by BigPun86** [react-native-community/react-native-camera#1807]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
1. Take a picture with android
    const data = await this.camera.takePictureAsync(this.options); 
    if(data && data.uri) this.setState({ image: data.uri } )
2. display the image within a Image component
3. Check the rotation of the image => in my case it is always rotated by 90deg

### Expected behaviour
The image should not be rotated

### Actual behaviour
The image is rotated by 90deg

### Environment
- **React Native version 53.3**:
- **Google Nexus 5X - API 26 | Samsung Galaxy S5 | API 19

### react-native-camera
**Version**: 1.2.0

I have added the option fixOrientation as well, which didn't make any difference

**Comment by XaviSmith** [comment]
+1, also getting this error

**Comment by Cygnus2112** [comment]
+1

**Comment by mcorner** [comment]
Even with 1.6.3 (which contained a fix), this is still broken for me on some android devices (Samsung for instance).

const options = { quality: 0.5, base64: true, orientation: RNCamera.Constants.ORIENTATION_UP };
const data = await this.camera.takePictureAsync(options);

fixOrientation: true does work, but it is incredibly slow (6 seconds) because it is rotating the image afterwards.

**Comment by scarlac** [comment]
There seems to be general issues with orientation on both iOS and Android. It seems we are adding more and more properties to workaround these issue (`orientation`, `fixOrientation`, `forceUpOrientation`) while the underlying issue remains. The default setup is broken so it would be really great if these issues were fixed, as it's not viable fix to add additional processing to taking photos (it's already quite slow).

**Comment by andresmtz98** [comment]
+1 :/

**Comment by sibelius** [comment]
can you try latest version

we fixed some orientation issues again

**Comment by andresmtz98** [comment]
https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a

This is a global issue

**Comment by asanz8** [comment]
I fixed this behavior on Samsung S3 Mini using:

`orientation: 'portrait', fixOrientation: true`

Version 2.9.0

**Comment by guildeassis** [comment]
I solved this problem, but it was not so simple. You need to use: `exif: true`  and get the `exif.Orientation` like it:
```
takePicture = async() => {
    ...
      const options = { exif: true };
      const data = await this.camera.takePictureAsync(options);
      this.setState({orientValue: data.exif.Orientation});
    ...
}
```
Now, you can use `this.state.orientValue` inside a function and customize the Image like this:
```
<Image
    style={{ transform: [{ rotate: this.rotateImage() }] }}
/>
```
And finally, rotateImage:
```
rotateImage() {
    let exifOrientation = this.state.orientValue;
    let degRotation;
    switch (exifOrientation) {
	case 3:
	       degRotation = "180deg"
	       break;
	case 4:
		degRotation = "180deg"
		break;
	case 5:
		degRotation = "90deg"
		break;
	case 6:
		degRotation = "90deg"
		break;
	case 7:
		degRotation = "270deg"
		break;
	case 8:
		degRotation = "270deg"
		break;
	default: 
		degRotation = "0deg"
	}
   return degRotation;
}
```
Why rotate this deg? The image explain:
![exif](https://user-images.githubusercontent.com/36502930/59545199-9c2d7c80-8ef1-11e9-85c2-f543e9f6aa07.png)

Note: this only rotates and does not reverse. I think it will work on most cell phones. Am I right?
Note 2: If you save the image to a server, then you need to rotate there as well. That way it only rotates in the react native app. In my case, i use laravel intervention for fix the orientation in the back-end.

**Comment by Michaelvilleneuve** [comment]
Hi, still seeing this issue on a Samsung Galaxy Note 3, Android 5.0
It appears that it is very specific to some Android and particularly samsung devices as always. 
Here is how we are taking the photo : 
```
const data = await this.camera.takePictureAsync({
                quality: 0.4,
                base64: true,
                width: 1080,
                fixOrientation: true,
});
```

**Comment by MateusAndrade** [comment]
@Michaelvilleneuve you tested if ```writeExif``` solves this? I remember having a similar problem, and using this with ```fixOrientation``` worked for me.

**Comment by fabriziobertoglio1987** [comment]
> https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a
> 
> This is a global issue

in fact [version 2.9.0 of ReactNativeCamera adds those Exif feature](https://github.com/react-native-community/react-native-camera/releases/tag/v2.9.0) from the above stackoverflow discussion

**Comment by HappyCMD** [comment]
@n1ru4l I dont think it has, I'm having the same issue on v 3.6.0

**Comment by HauLuu** [comment]
@n1ru4l It actually not, I'm on v3.7.2

      const options = {
        quality: ,
        base64: true,
        orientation: RNCamera.Constants.Orientation.auto,
        pauseAfterCapture: true,
        fixOrientation: true
      };
      const data = await this.camera.takePictureAsync(options);

**Comment by khaledalam** [comment]
this will save your time :)
```
const options = {
          quality: 1,
          base64: true,
          orientation: RNCamera.Constants.Orientation.portrait,
          fixOrientation: true
};
const data = await props.mycamera.current.takePictureAsync(options);
```

**Comment by frankcodev** [comment]
Hi, this worked for me:

`const options = { quality: 0.5, base64: true,  mirrorImage: true, fixOrientation: true };`

**Comment by vipu-sa** [comment]
> I fixed this behavior on Samsung S3 Mini using:
> 
> `orientation: 'portrait', fixOrientation: true`
> 
> Version 2.9.0

I have not working this in android.

**Comment by ashishprasad2163** [comment]
I was getting this error on using the front camera only. 
so this worked for me,
        mirrorImage: frontCamera  ? true : false,
        forceUpOrientation: frontCamera  ? true : false,
        fixOrientation: frontCamera  ? true : false,

**Comment by rajan-keypress** [comment]
const data = await takePicture({
        mirrorImage: true,
      }); work for me
