### ISSUE TITLE
RNCamera.checkVideoAuthorizationStatus is not a function - iOS

### ISSUE THREAD

**Issue by davebro** [react-native-community/react-native-camera#2413]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Migrating to v2.11.1 from a much older v0.10.0, I have gone through all the install steps in the README, our project has all the required keys in our Info.plist files. I have also manually linked the project iOS and the project builds successfully. Android runs just fine, iOS however throws an error at runtime when `RNCamera.checkVideoAuthorizationStatus` is called:
 
![IMG_05F873D3C51F-1 (1)](https://user-images.githubusercontent.com/3409406/62493350-b9f6bf80-b785-11e9-9842-55b7920b27bd.JPEG)

Has this function been deprecated in newer versions, and if so, is there a more preferred way to check for permissions on iOS? A quick search for `checkVideoAuthorizationStatus` in the react-native-camera repo shows the function is still part of the project in some capacity.

**Comment by MateusAndrade** [comment]
Hi @davebro , i think this method has been deprecated or removed on the newer versions. You tried using ```refreshAuthorizationStatus()?```. Please, give a look at: https://react-native-community.github.io/react-native-camera/docs/api and let me know if this helps you.

**Comment by takitus** [comment]
This is an issue on version 0.60.0 + of react-native. You can get around this for now by using a version lower than 60 (59.8 works). 

react-native init ProjName --version react-native@0.59.8

Ive obviously run into the same issue. Hopefully it gets rectified sooner rather than later.

**Comment by MateusAndrade** [comment]
> Ive obviously run into the same issue. Hopefully it gets rectified sooner rather than later.

Thanks for letting us know that. 

@davebro which version of react-native are you using?

**Comment by davebro** [comment]
@MateusAndrade Currently we are on react-native 0.58.6. We are upgrading shortly to 0.59.10 and I have also tested on that version, same result.

**Comment by takitus** [comment]
if you are using an older version, just make sure you use 
"react-native link react-native-camera". 

It should resolve that issue

**Comment by davebro** [comment]
In older versions of react-native-camera, I noticed whereas `checkVideoAuthorizationStatus` was a static function accessed like so:
```
import Camera from 'react-native-camera';

Camera.checkVideoAuthorizationStatus().then((isAuthorized) => {
    ...
})
```

The current version provides `refreshAuthorizationStatus` and requires an instance of RNCamera from `import { RNCamera } from 'react-native-camera';` in order to use it.

From the docs here https://react-native-community.github.io/react-native-camera/docs/api it seems like `refreshAuthorizationStatus` provides similar functionality? I'll have to test that, but if anyone has further insights, that'd be most helpful.

**Comment by davebro** [comment]
@takitus Yes, `react-native link react-native-camera` has been run several times but still shows the same error. I've also manually linked the library, but with no success regarding `checkVideoAuthorizationStatus `.

**Comment by takitus** [comment]
```
react-native init ProjName --version react-native@0.59.10
cd ProjName
yarn add react-native-camera
react-native link react-native-camera
```
*add permissions into info.plist*
```
<key>NSCameraUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Your message to user when the photo library is accessed for the first time</string>
<key>NSMicrophoneUsageDescription</key>
<string>Your message to user when the microphone is accessed for the first time</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Your message to user when the photo library is accessed for the first time</string>
```
* run
`react-native run-ios`

**Comment by davebro** [comment]
@takitus Thanks for the install instructions. I set up a test project real quick and followed your instructions exactly, then tried referencing `RNCamera.checkVideoAuthorizationStatus()` in App.js, which gave me the same error referenced above.

![IMG_05F873D3C51F-1 (1)](https://user-images.githubusercontent.com/3409406/62574468-694a9980-b84d-11e9-9f73-9bbec05d596e.JPEG)

Any suggestions? Thanks for your help.

**Comment by takitus** [comment]
You shouldn't have to call that function manually. 

Try copy pasting the app.js from the basic example to the new test project you just made and running it. It should run, function, and pop up all necessary permission requests:

https://github.com/react-native-community/react-native-camera/blob/master/examples/basic/App.js

**Comment by takitus** [comment]
Also, if you need to re-check permissions, you can use refreshAuthorizationStatus()

https://react-native-community.github.io/react-native-camera/docs/api#refreshauthorizationstatus

**Comment by davebro** [comment]
@takitus Thank you for the info, that makes sense. One last question, if I wanted to pre-check for camera permissions on iOS before showing the official permissions modal, for instance to show our own modal first, is using _react-native-community/react-native-permissions_ the accepted way of doing that for iOS from this library's standpoint? Or is that what `refreshAuthorizationStatus` is for? Not seeing any examples of how that function works. I know we have _PermissionsAndroid_ on Android from react-native, but I'm wondering specifically about iOS.

That was the whole point of using `checkVideoAuthorizationStatus`, which is obviously now deprecated :)

**Comment by williamgoodhew** [comment]
I am getting the same error
`TypeError: CameraManager.checkVideoAuthorizationStatus is not a function`

I am using React-Native: 0.61.5
react-native-camera: 3.15.1

**Comment by Gerrist** [comment]
Are there any updates regarding this issue? Like others, I also successfully manually installed everything for IOS, but I still get the 'CameraManager.checkVideoAuthorizationStatus is not a function' error.

**Comment by wxsms** [comment]
Manually install fixed this issue.

ref: #2275, #2248
