### ISSUE TITLE
undefined is not an object (evaluating 'PropTypes.oneOfType')

### ISSUE THREAD

**Issue by israelidanny** [react-native-community/react-native-camera#303]
### Steps to reproduce
1. Installed the module according to README
2. Put it into a working simple app I have in a component like so:

```
import React from 'react'
import { StyleSheet, View } from 'react-native'
import paddingTop from '../constants/paddingTop'
import Camera from 'react-native-camera'
const { Component, PropTypes } = React

export default class Capture extends Component {
  static propTypes = {
    navigator: PropTypes.object.isRequired
  };

  render() {
    return (
      <View style={[styles.container, { paddingTop }]}>
        <Camera
          ref="camera"
          style={styles.camera}
        />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column'
  },
  camera: {
    flex: 1
  }
})
```
### Expected behaviour

The camera module should work
### Actual behaviour

I get the following errors:

```
2016-05-29 19:19:41.273 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'PropTypes.oneOfType')
2016-05-29 19:19:41.274 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'PropTypes.oneOfType')
2016-05-29 19:19:41.294 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module.
2016-05-29 19:19:41.294 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module.
```

I don't even have to use the `<Camera />` component to get this, all I need to do is import it. 
### Environment
- **Node.js version**: node v5.6.0
- **React Native version**: react-native@0.26.0
- **React Native platform + platform version**: iOS 
### react-native-camera

**Version**: react-native-camera@0.3.8

**Comment by israelidanny** [comment]
I think I have a clue here:
http://stackoverflow.com/questions/37320748/upgrading-to-26-broke-the-dependencies

Apparently starting from `react-native@0.26.0` it should be `var React = require('react')` and not `var React = require('react-native')`

**Comment by rt2zz** [comment]
master is pretty unstable. We will be releasing v1 beta soon, but we need a help to get things stable and production ready. 

Not sure what your timeline is but I would install from master for now. We do not have any more breaking changes planned so the api should be pretty stable.

**Comment by pixelgamma** [comment]
It seems if you've installed the module from **npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save** you should have a working version. If you've installed from **npm install react-native-camera --save**, you'll get the error you mentioned with RN v0.26.

**Comment by israelidanny** [comment]
@rt2zz what *is* the timeline that this component looks like for now?

Is iOS any more stable than Android? 

What kind of help do you need?

**Comment by charpeni** [comment]
Can you test with this branch #304, it seems stable on both platforms to me.

**Comment by israelidanny** [comment]
Actually, on iOS so far I had absolutely no issues. I'll test #304 later on, but so far it's been fantastic.

**Comment by NLebedev** [comment]
I had the same error, running on react-native 0.27 but as @pixelgamma mentioned installing with npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save fixed the issue

**Comment by logicminds** [comment]
also receiving this error with react-native 0.46.

```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-camera": "^0.9.4",
    "react-navigation": "^1.0.0-beta.12"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12",
    "reactotron-react-native": "^1.12.1"
  },
```

**Comment by logicminds** [comment]
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

Should we be importing like `import PropTypes from 'prop-types';`

**Comment by wootwoot1234** [comment]
I think #811 PR fixes this.  I'm testing it now....

**Comment by devSeb** [comment]
I have this error 
Install prop-types no resolve this.

my package.json
```
"dependencies": {
		"prop-types": "^15.6.0",
		"react": "16.0.0",
		"react-native": "0.50.4",
		"react-native-camera": "^0.6.0"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0"
	},
```
error : 
<unknown> react-native-camera/index.js:75:22

**Comment by miguel-duarte** [comment]
this worked for me:
in node_modules\react-native-camera\index.js

- removed PropTypes from `import React, { Component, PropTypes } from 'react';`
- add `import PropTypes from 'prop-types';`

in package.json

- add in "dependencies" `"prop-types": "^15.6.0"`

in QRCode.js changed to :

[QRCode.js.txt](https://github.com/lwansbrough/react-native-camera/files/1513596/QRCode.js.txt)

**Comment by ivansnek** [comment]
thanks @NLebedev current working with `react-native: ^0.50.0` and using:

`npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save `

fixed my issue too. Also I have to mention that I installed manually not using the `link` command.

**Comment by sibelius** [comment]
Fixed on master

**Comment by hazeeb** [comment]
```
react-native: "0.50.3"
react-native-camera: "0.6.0",
```

I'm having the same issue, Installed module with below command.
`npm install react-native-camera --save`
 
Tried importing proptypes, but no use.

**Comment by nicemanis** [comment]
This issue is not resolved yet. If you install 0.6.0 version, then you get the prop type error, if you install the git version, then you get the previously mentioned error for cameraview

**Comment by sibelius** [comment]
Check RNCameraExample

You need jitpack

**Comment by Kennytian** [comment]
@hazeeb
allprojects {
    repositories {
        jcenter()
    +     maven {
    +        url "https://maven.google.com"
    +    }
    }
}

**Comment by yoesak** [comment]
I follow miguel-duarte, and it does work. Don't forget to look at attached file QRCode.txt.

**Comment by douggard** [comment]
Same error as @hazeeb.
